### ISSUE TITLE
Option to sort entries in tables

### ISSUE THREAD

**Issue by alexxwhyy** [Christopher22/shelby#5]
Tales should have an option behind every column name to sort the entries. For example, it should be possible to sort the uploaded documents according to the date created or lets say alphabetically.
<img width="778" alt="Screenshot 2024-04-18 at 15 56 14" src="https://github.com/Christopher22/shelby/assets/127108141/4e9c94c9-3700-4ea2-b8c8-af3453aeea83">

**Comment by Christopher22** [comment]
Yes, that would be convenient, indeed! In the backend, everything is prepared. I will start working on the frontend now!

**Comment by Christopher22** [comment]
That is now included in Version 0.1.2 :)
