### ISSUE TITLE
Option to open and view groups

### ISSUE THREAD

**Issue by alexxwhyy** [Christopher22/shelby#6]
It would be great to be able to click on the distinct groups and list their contents. So, the user can see the persons belonging to a group.
At least there should be a column called "group" in the table "persons" where it says to which group the person or institution belongs.

**Comment by Christopher22** [comment]
Good news: With the newest version (already published in the Docker repository), this feature is implemented. Could you check it out and reopen the issue if still persistent?

**Comment by alexxwhyy** [comment]
Unfortunately, I cannot click on the groups nor can I see to which group a person belongs. Tried it several times using Safari as well as Chrome.

<img width="1188" alt="Screenshot 2024-04-19 at 00 22 31" src="https://github.com/Christopher22/shelby/assets/127108141/7c005b24-016e-4a3b-bf61-329ba0ce2372">
<img width="741" alt="Screenshot 2024-04-19 at 00 22 11" src="https://github.com/Christopher22/shelby/assets/127108141/7748b619-5339-43f9-81f0-9219e66b5163">

**Comment by Christopher22** [comment]
Hmm, thats how it looks in the newest version: ![image](https://github.com/Christopher22/shelby/assets/8844682/2fd48af3-0b14-41b7-9011-969f72f4f8ea)

We certainly should include a version indicator to simplify bug tracking in the future!

**Comment by alexxwhyy** [comment]
I agree! Maybe I am stuck on the old version. Do I have to update manually?

**Comment by Christopher22** [comment]
Yes, you have. However, just pulling the "latest" tag from the Docker repository should do the trick :)

**Comment by alexxwhyy** [comment]
Perfect. It would be great if you always pull the latest tag yourself after you pushed a new version as you have access to the container manager yourself. Otherwise, I am afraid, changes on shelby might be overseen by the users accidentally. You can then immediately check if the system runs properly on the "server". Thank you!
